[project]
name = "multiturn-rl"
version = "0.1.0"
description = "Multiturn RL experiments"
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["verl[gpu,vllm,math]", "flashinfer-python"]

[tool.uv.sources]
verl = { path = "verl", editable = true }
flashinfer-python = { index = "flashinfer" }
multiturn-rl = { workspace = true }

[[tool.uv.index]]
name = "flashinfer"
url = "https://flashinfer.ai/whl/cu124/torch2.6/"

# -------------------------------
# tool.ruff - Linting configuration
# -------------------------------
[tool.ruff]
line-length = 120
[tool.ruff.lint]
isort = { known-first-party = ["verl"] }
# c.f. https://github.com/vllm-project/vllm/blob/ce8d6b75fc0586045df75ee1568a5b5f9957251b/pyproject.toml
select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # isort
    "I",
    "G",
]
ignore = [
    # star imports
    "F405",
    "F403",
    # lambda expression assignment
    "E731",
    # Loop control variable not used within loop body
    "B007",
    # f-string format
    "UP032",
    # Can remove once 3.10+ is the minimum Python version
    "UP007",
    # `.log()` statement uses f-string
    "G004",
]
